services:
  - type: web
    name: shini
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shini-db
          property: connectionString
      - key: VK_TOKEN
        sync: false
      - key: VK_CHAT_ID
        value: "197"
      - key: VK_PEER_ID
        sync: false
      - key: VK_API_VERSION
        value: "5.199"
      - key: CORS_ORIGINS
        value: https://shini-1.onrender.com

databases:
  - name: shini-db
    plan: free
    databaseName: shini
    user: shini
